# Generated by Django 5.2.10 on 2026-01-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Product Title / प्रोडक्ट का नाम')),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Short Description / संक्षिप्त विवरण')),
                ('description', models.TextField(blank=True, help_text='Supports HTML formatting', verbose_name='Full Description / पूरा विवरण')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Featured Image / मुख्य फोटो')),
                ('is_pan_india', models.BooleanField(default=True, help_text='If checked, available in all states/cities', verbose_name='Available Pan India / पूरे भारत में उपलब्ध')),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Full Price / पूरी कीमत (₹)')),
                ('half_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='50% Advance Price / अग्रिम राशि (₹)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Price (for discount display) / मूल कीमत')),
                ('allow_half_payment', models.BooleanField(default=True, verbose_name='Allow 50% Advance / 50% अग्रिम भुगतान')),
                ('form_title', models.CharField(default='Application Form', max_length=200, verbose_name='Form Title / फॉर्म का नाम')),
                ('form_description', models.CharField(blank=True, max_length=500, verbose_name='Form Description / फॉर्म का विवरण')),
                ('form_schema', models.JSONField(blank=True, default=list, help_text='DO NOT EDIT MANUALLY - Use Visual Form Builder below', verbose_name='Form Fields (JSON)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon')], default='draft', max_length=20, verbose_name='Status / स्थिति')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured / विशेष')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popular / लोकप्रिय')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('processing_time', models.CharField(blank=True, help_text='e.g., 3-5 working days', max_length=100, verbose_name='Processing Time / प्रोसेसिंग समय')),
                ('documents_required', models.TextField(blank=True, verbose_name='Documents Required / आवश्यक दस्तावेज')),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_cities', models.ManyToManyField(blank=True, related_name='products', to='locations.city', verbose_name='Available Cities / उपलब्ध शहर')),
                ('available_states', models.ManyToManyField(blank=True, related_name='products', to='locations.state', verbose_name='Available States / उपलब्ध राज्य')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='Category / श्रेणी')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategory', verbose_name='Subcategory / उप-श्रेणी')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.product')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order'],
            },
        ),
    ]
