# Generated by Django 5.2.10 on 2026-01-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_link',
            field=models.URLField(blank=True, verbose_name='YouTube Video Link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_half_payment',
            field=models.BooleanField(default=True, verbose_name='Allow 50% Advance'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_cities',
            field=models.ManyToManyField(blank=True, related_name='products', to='locations.city', verbose_name='Available Cities'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_states',
            field=models.ManyToManyField(blank=True, related_name='products', to='locations.state', verbose_name='Available States '),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Supports HTML formatting', verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='documents_required',
            field=models.TextField(blank=True, verbose_name='Documents Required'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='form_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Form Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='form_title',
            field=models.CharField(default='Application Form', max_length=200, verbose_name='Form Title '),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Full Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_pan_india',
            field=models.BooleanField(default=True, help_text='If checked, available in all states/cities', verbose_name='Available All India'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Price (for discount display)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processing_time',
            field=models.CharField(blank=True, help_text='e.g., 3-5 working days', max_length=100, verbose_name='Processing Time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategory', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Product Title'),
        ),
    ]
