# Generated by Django 5.2.10 on 2026-01-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_youtube_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='half_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Partial Price'),
        ),
    ]
