# Generated by Django 5.2.10 on 2026-01-23 06:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_half_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Supports HTML formatting', verbose_name='Full Description'),
        ),
    ]
