# Generated by Django 5.2.10 on 2026-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_privacy_policy',
            field=models.TextField(blank=True, verbose_name='Data Privacy Policy'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_its_work',
            field=models.TextField(blank=True, verbose_name='How It Works'),
        ),
    ]
