# Generated by Django 5.2.10 on 2026-02-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_data_privacy_policy_product_how_its_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='documents_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='how_its_work',
        ),
    ]
