# Generated by Django 5.2.10 on 2026-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_data_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_privacy_policy',
            field=models.TextField(blank=True, verbose_name='Data Privacy Policy'),
        ),
        migrations.AddField(
            model_name='product',
            name='documents_required',
            field=models.TextField(blank=True, verbose_name='Documents Required'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_its_work',
            field=models.TextField(blank=True, verbose_name='How It Works'),
        ),
    ]
