# Generated by Django 5.2.10 on 2026-02-21 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_data_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Data Privacy Policy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='documents_required',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Documents Required'),
        ),
        migrations.AlterField(
            model_name='product',
            name='how_its_work',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='How It Works'),
        ),
    ]
