# Generated by Django 5.2.10 on 2026-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_data_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_template',
            field=models.TextField(blank=True, help_text='Use {{field_name}} placeholders. e.g. <b>Name:</b> {{full_name}}<br><b>City:</b> {{city}}', verbose_name='Preview Template (HTML)'),
        ),
    ]
