# Generated by Django 5.2.10 on 2026-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_preview_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_preview_enabled',
            field=models.BooleanField(default=True, help_text='Disable karne par user ko performa preview nahi dikhega', verbose_name='Enable Performa Preview'),
        ),
    ]
