# Generated by Django 5.2.10 on 2026-05-27 12:51

from django.db import migrations, models


def migrate_category_to_categories(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.category_id:
            product.categories.add(product.category_id)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_hindi_fields'),
        ('products', '0016_revert_preview_template_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products_categories', to='categories.category', verbose_name='Categories'),
        ),
        migrations.RunPython(migrate_category_to_categories, reverse_code=migrations.RunPython.noop),
    ]
