# Generated by Django 5.2.10 on 2026-05-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_hindi_fields'),
        ('products', '0017_product_categories_product_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategory', verbose_name='Subcategory'),
        ),
    ]
