# Generated by Django 5.2.15 on 2026-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_hindi_fields'),
        ('products', '0018_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Select one or more subcategories for this product', related_name='products_subcategories', to='categories.subcategory', verbose_name='Subcategories'),
        ),
    ]
