# Generated by Django 5.2.10 on 2026-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_fix_order_user_email_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
