# Generated by Django 5.2.15 on 2026-07-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordertask_ordertaskdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertask',
            name='requires_file_upload',
            field=models.BooleanField(default=False),
        ),
    ]
