# Generated by Django 5.2.10 on 2026-01-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Supports HTML formatting', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
