# Generated by Django 5.2.10 on 2026-01-23 06:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Supports HTML formatting', verbose_name='Description'),
        ),
    ]
