# Generated by Django 5.2.10 on 2026-01-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hi', models.CharField(blank=True, max_length=100, verbose_name='Name (Hindi)')),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(help_text='State code like MH, DL, KA', max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hi', models.CharField(blank=True, max_length=100, verbose_name='Name (Hindi)')),
                ('slug', models.SlugField()),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1 (Metro)'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], default='tier_2', max_length=10)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
                'unique_together': {('state', 'slug')},
            },
        ),
    ]
