# Generated by Django 5.2.10 on 2026-01-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_hi',
        ),
    ]
