# Generated by Django 5.2.10 on 2026-02-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
        ('products', '0009_alter_product_data_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='products.product'),
        ),
    ]
